// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmtucobwyckjivtdskkl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtdHVjb2J3eWNraml2dGRza2tsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNDMxNTIsImV4cCI6MjA2NDYxOTE1Mn0.A_ZsiRZyG9kfrtmcoArBwiiGpzj3sEjyJhuY57KPWK0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);